export interface BlueprintComponent {
  id: string;
  name: string;
  partNumber: string;
  panelId: number;
  material: string;
  tolerance: string;
  mass: string;
  description: string;
  specs: Record<string, string>;
}

export interface BlueprintPanelData {
  id: number;
  title: string;
  subtitle: string;
  standard: string;
  projection: string;
  scale: string;
  components: BlueprintComponent[];
  kinematics?: {
    dof: string;
    range: string;
    torque: string;
    speed: string;
  };
  dimensions: {
    label: string;
    value: string;
  }[];
}

export const BLUEPRINT_METADATA = {
  documentNo: 'INX-R9-ARM-M07',
  revision: '3.2',
  date: '2026-09-12',
  classification: 'RESTRICTED / MANUFACTURING SPEC',
  standard: 'ISO 2768-mK / ASME Y14.5M-2018',
  designer: 'Advanced Robotics Engineering Group (Apple Robotics × Tesla Optimus Benchmark)',
  title: 'AAA HUMANOID ROBOTIC ARM — WIREFRAME BLUEPRINT & MECHANICAL REFERENCE',
  totalLength: '740 mm',
  totalMass: '3.42 kg',
  nominalPayload: '6.50 kg',
  peakPayload: '12.00 kg',
  totalDof: '19 Active Degrees of Freedom (7 Arm + 12 Hand)',
  busVoltage: '48V DC High-Density Bus',
};

export const BLUEPRINT_PANELS: BlueprintPanelData[] = [
  {
    id: 1,
    title: 'PANEL 1 — FULL ARM OVERVIEW',
    subtitle: 'Front Orthographic Engineering Projection & Proportional Center Axes',
    standard: 'ASME Y14.5M',
    projection: 'First Angle Orthographic',
    scale: '1:2.5',
    dimensions: [
      { label: 'Total Arm Length', value: '740 mm' },
      { label: 'Shoulder Center to Elbow Axle', value: '320 mm' },
      { label: 'Elbow Axle to Wrist Center', value: '260 mm' },
      { label: 'Wrist Center to Finger Tip (Digit III)', value: '160 mm' },
      { label: 'Shoulder Pauldron Max Diameter', value: 'Ø 138 mm' },
      { label: 'Upper Arm Bicep Width', value: '88 mm' },
      { label: 'Elbow Hinge Chassis Width', value: '74 mm' },
      { label: 'Forearm Keel Width', value: '72 mm' },
      { label: 'Wrist Spherical Collar Diameter', value: 'Ø 56 mm' },
      { label: 'Hand Metacarpal Span', value: '85 mm' },
    ],
    kinematics: {
      dof: '7 DOF Arm + 12 DOF Hand = 19 DOF Total',
      range: 'Reach Radius: 740 mm (Hemispherical Work Envelope)',
      torque: 'Shoulder: 120 Nm | Elbow: 78 Nm | Wrist: 28 Nm',
      speed: 'End-effector Linear Velocity: 3.8 m/s',
    },
    components: [
      {
        id: 'c1-1',
        name: 'Shoulder Spherical Joint Assembly',
        partNumber: 'INX-SH-001',
        panelId: 1,
        material: '7075-T6 CNC Aluminum + PEEK Ceramic Pauldron',
        tolerance: '±0.015 mm',
        mass: '1,120 g',
        description: 'Multi-axis high-torque shoulder actuator stack supporting 3-DOF spherical rotation.',
        specs: {
          'Gear Ratio': '100:1 Harmonic Drive',
          'Peak Torque': '120 Nm',
          'Cooling': 'Convective Micro-Fin Housing',
        },
      },
      {
        id: 'c1-2',
        name: 'Upper Arm Skeletal Truss & Bicep Shell',
        partNumber: 'INX-UA-002',
        panelId: 1,
        material: 'Milled 7075-T6 I-Beam Spar + Aerodynamic Polycarbonate Shell',
        tolerance: '±0.025 mm',
        mass: '480 g',
        description: 'Tapered structural member housing main DC bus power rail and EtherCAT signal conduits.',
        specs: {
          'Bending Rigidity': '14,200 N/mm',
          'Standoff Gap': '3.5 mm Air-Gap',
          'Conduit Dia': '2x Ø 12 mm Braided Channels',
        },
      },
      {
        id: 'c1-3',
        name: 'Elbow Double-Clevis Hinge Mechanism',
        partNumber: 'INX-EL-003',
        panelId: 1,
        material: 'Ti-6Al-4V Grade 5 Titanium Clevis Forks',
        tolerance: '±0.008 mm',
        mass: '560 g',
        description: 'Double-axis clevis joint with cross-roller bearing and integrated deceleration damper.',
        specs: {
          'Axle Pin': 'Ø 18 mm Case-Hardened Steel',
          'Range': '0° to 135° Flexion',
          'Hard Stop': 'Mechanical 137.5° CNC Lug',
        },
      },
      {
        id: 'c1-4',
        name: 'Forearm Internal Chassis & Actuator Bays',
        partNumber: 'INX-FA-004',
        panelId: 1,
        material: '7075-T6 Triangulated CNC Spaceframe Box',
        tolerance: '±0.020 mm',
        mass: '620 g',
        description: 'Rigid skeleton mounting dual linear roller-screw actuators and wrist transmission rods.',
        specs: {
          'Actuation': 'Dual Inverted Roller-Screws',
          'Venting': 'Triple Laminar Heat Slots',
          'Armor': 'Floating 2.8 mm Gauntlet Keel',
        },
      },
      {
        id: 'c1-5',
        name: '3-DOF Spherical Wrist Differential',
        partNumber: 'INX-WR-005',
        panelId: 1,
        material: 'Aircraft 6061-T6 + Stainless Steel Bearings',
        tolerance: '±0.010 mm',
        mass: '290 g',
        description: 'Compact 3-axis virtual center gimbal delivering Yaw, Pitch, and Roll.',
        specs: {
          'Roll Range': '-90° to +90°',
          'Pitch Range': '-75° to +75°',
          'Yaw Range': '-30° to +40°',
        },
      },
      {
        id: 'c1-6',
        name: 'Articulated 5-Digit Humanoid Hand',
        partNumber: 'INX-HD-006',
        panelId: 1,
        material: 'Carbon-Reinforced PEEK + Titanium Metacarpal Frame',
        tolerance: '±0.012 mm',
        mass: '350 g',
        description: 'High-dexterity robotic hand with 5 independently actuated digits and tactile sensor domes.',
        specs: {
          'Grip Force': '85 N (Power Grip)',
          'Tendon System': 'Tungsten-Dyneema Hybrid 1.2 mm',
          'Tactile Res': '16-Point Capacitive Array/Tip',
        },
      },
    ],
  },
  {
    id: 2,
    title: 'PANEL 2 — MULTIPLE ORTHOGRAPHIC VIEWS',
    subtitle: 'Front, Lateral Side, Rear Dorsal & Internal Skeleton Projections',
    standard: 'ISO 128-30',
    projection: 'Third Angle Multi-View',
    scale: '1:3.0',
    dimensions: [
      { label: 'Lateral Profile Depth (Shoulder)', value: '142 mm' },
      { label: 'Lateral Profile Depth (Elbow)', value: '82 mm' },
      { label: 'Rear Pauldron Exhaust Flare', value: '118 mm' },
      { label: 'Skeleton Chassis Width (Internal)', value: '46 mm' },
      { label: 'Armor Wall Thickness', value: '2.80 mm' },
    ],
    components: [
      {
        id: 'c2-1',
        name: 'Front Orthographic Silhouette',
        partNumber: 'VIEW-ORT-01',
        panelId: 2,
        material: 'Outer Ceramic PEEK Shell with Signature Satin Finish',
        tolerance: '±0.05 mm',
        mass: 'N/A',
        description: 'Shows aerodynamic frontal profile designed to minimize aerodynamic drag and human interference.',
        specs: { 'Visible Seams': '0.8 mm Controlled Parting Lines' },
      },
      {
        id: 'c2-2',
        name: 'Lateral Side Silhouette',
        partNumber: 'VIEW-ORT-02',
        panelId: 2,
        material: 'Dual Layer (Polymer Outer + Aluminum Core)',
        tolerance: '±0.05 mm',
        mass: 'N/A',
        description: 'Exposes mechanical hinge negative space, elbow clearance arc, and wrist flex range.',
        specs: { 'Elbow Clearance': '14 mm Negative Relief' },
      },
      {
        id: 'c2-3',
        name: 'Rear Dorsal View',
        partNumber: 'VIEW-ORT-03',
        panelId: 2,
        material: 'Thermal Radiation Heat Sinks & Cable Exit Ports',
        tolerance: '±0.05 mm',
        mass: 'N/A',
        description: 'Depicts rear cooling louvers, wiring gland entry, and tricep damper bracket hardpoints.',
        specs: { 'Heat Dissipation': '45 W Max Thermal Load' },
      },
      {
        id: 'c2-4',
        name: 'Internal Skeleton View (Armor Stripped)',
        partNumber: 'VIEW-ORT-04',
        panelId: 2,
        material: 'CNC 7075-T6 Aerospace Aluminum Skeleton',
        tolerance: '±0.010 mm',
        mass: '2,140 g (Skeleton Only)',
        description: 'Complete mechanical skeleton revealing internal harmonic drives, crossed-roller bearings, and roller screws.',
        specs: { 'Structural Factor of Safety': '2.85x at Peak Acceleration' },
      },
    ],
  },
  {
    id: 3,
    title: 'PANEL 3 — SHOULDER EXPLODED ASSEMBLY',
    subtitle: 'Exploded Vertical Stacking, Harmonic Reducer & Motor Stator Assembly',
    standard: 'ASME Y14.38',
    projection: 'Exploded Orthographic Axis',
    scale: '1:1.8',
    dimensions: [
      { label: 'Mounting Flange Bolt Circle', value: 'PCD Ø 112 mm (8x M4)' },
      { label: 'Bearing Outer Diameter', value: 'Ø 98.00 mm' },
      { label: 'Bearing Inner Bore', value: 'Ø 72.00 mm' },
      { label: 'Harmonic Drive Length', value: '44.5 mm' },
      { label: 'Wiring Center Pass-Through', value: 'Ø 28.0 mm Hollow Shaft' },
    ],
    kinematics: {
      dof: '3 DOF (Pitch, Yaw, Roll)',
      range: 'Pitch: -60° to +180° | Roll: -90° to +90° | Yaw: -45° to +135°',
      torque: 'Nominal: 68 Nm | Peak: 120 Nm',
      speed: 'Max Output: 240 deg/sec',
    },
    components: [
      {
        id: 'c3-1',
        name: 'Outer Ceramic Pauldron Cowl',
        partNumber: 'SH-EXP-01',
        panelId: 3,
        material: 'Silicon Nitride Ceramic-Reinforced Polymer (White)',
        tolerance: '±0.03 mm',
        mass: '185 g',
        description: 'Protective top shell shielding primary harmonic drive from external impact.',
        specs: { 'Impact Resistance': 'IK08 Rated', 'Wall Thickness': '2.8 mm' },
      },
      {
        id: 'c3-2',
        name: 'Inner Floating Pauldron Liner',
        partNumber: 'SH-EXP-02',
        panelId: 3,
        material: 'Anodized 6061-T6 Aluminum (Titanium Grey)',
        tolerance: '±0.02 mm',
        mass: '94 g',
        description: 'Intermediate acoustic dampening liner isolating motor magnetic hum.',
        specs: { 'Isolation': 'Neoprene Vibration Ring' },
      },
      {
        id: 'c3-3',
        name: 'Crossed-Roller Bearing Dual Race',
        partNumber: 'SH-EXP-03',
        panelId: 3,
        material: 'High-Carbon Chromium Bearing Steel (GCr15)',
        tolerance: '±0.003 mm (P4 Precision)',
        mass: '240 g',
        description: 'Preloaded crossed-roller bearing absorbing simultaneous radial, axial, and moment loads.',
        specs: { 'Dynamic Radial Rating': '18.4 kN', 'Static Moment': '245 Nm' },
      },
      {
        id: 'c3-4',
        name: 'Harmonic Drive Circular Spline & Flexspline',
        partNumber: 'SH-EXP-04',
        panelId: 3,
        material: 'SNCM439 High-Tensile Alloy Steel flexspline',
        tolerance: '±0.005 mm',
        mass: '310 g',
        description: 'Zero-backlash strain-wave gear reducer yielding 100:1 transmission reduction.',
        specs: { 'Backlash': '< 10 arcsec', 'Reduction Ratio': '100:1' },
      },
      {
        id: 'c3-5',
        name: 'Frameless Brushless DC Motor Stator & Rotor',
        partNumber: 'SH-EXP-05',
        panelId: 3,
        material: 'Rare-Earth Neodymium Magnets + Low-Loss Silicon Steel Laminations',
        tolerance: '±0.010 mm',
        mass: '380 g',
        description: 'Direct-drive concentric torque motor with hollow central bore for slip ring wiring.',
        specs: { 'Continuous Power': '320 W', 'Motor Constant Km': '0.24 Nm/√W' },
      },
      {
        id: 'c3-6',
        name: 'Structural Clavicle Chassis Interface',
        partNumber: 'SH-EXP-06',
        panelId: 3,
        material: 'CNC Milled 7075-T6 Titanium Anodized Plate',
        tolerance: '±0.015 mm',
        mass: '210 g',
        description: 'Base mounting chassis securing shoulder actuator group to robot thoracic ribcage.',
        specs: { 'Fasteners': '8x M4 Grade 12.9 Socket Bolts' },
      },
      {
        id: 'c3-7',
        name: 'Dual Silicone Environmental O-Ring Seal',
        partNumber: 'SH-EXP-07',
        panelId: 3,
        material: 'Fluoroelastomer (FKM) 75 Shore A',
        tolerance: '±0.05 mm',
        mass: '12 g',
        description: 'Hermetic barrier preventing ingress of micro-particulates and humidity into bearing tracks.',
        specs: { 'Ingress Protection': 'IP67 Rated' },
      },
    ],
  },
  {
    id: 4,
    title: 'PANEL 4 — ELBOW DOUBLE HINGE MECHANISM',
    subtitle: 'Kinematic Flexion Study, Double Clevis Axle & Hydraulic Deceleration Damper',
    standard: 'ISO 4975',
    projection: 'Sectional & Exploded Orthographic',
    scale: '1:1.5',
    dimensions: [
      { label: 'Transverse Axle Diameter', value: 'Ø 18.00 mm (h6 fit)' },
      { label: 'Double Clevis Span (Internal)', value: '48.00 mm' },
      { label: 'Bearing Housing OD', value: 'Ø 42.00 mm' },
      { label: 'Damper Stroke Length', value: '38.00 mm' },
      { label: 'Rotational Stop Angle', value: '135.0° Flexion Stop' },
    ],
    kinematics: {
      dof: '1 Primary Rotary DOF (Flexion/Extension) + 1 Rotary Damper Assist',
      range: '0° (Full Extension) to 135° (Full Flexion)',
      torque: 'Nominal: 45 Nm | Peak: 78 Nm',
      speed: 'Max Angular Velocity: 310 deg/sec',
    },
    components: [
      {
        id: 'c4-1',
        name: 'Double-Clevis Outer Structural Fork',
        partNumber: 'EL-MECH-01',
        panelId: 4,
        material: 'Forged Ti-6Al-4V Grade 5 Titanium',
        tolerance: '±0.008 mm',
        mass: '235 g',
        description: 'Bilateral fork transferring elbow bending moments from humerus to radius/ulna.',
        specs: { 'Yield Strength': '880 MPa', 'Finite Element Factor': '3.2x' },
      },
      {
        id: 'c4-2',
        name: 'Transverse Hardened Pivot Axle',
        partNumber: 'EL-MECH-02',
        panelId: 4,
        material: 'AISI 52100 Bearing Steel (58-62 HRC)',
        tolerance: '±0.004 mm (h6)',
        mass: '92 g',
        description: 'Precision ground center axle with laser-etched alignment indices and dual M8 retention caps.',
        specs: { 'Surface Roughness': 'Ra 0.2 µm', 'Shear Capacity': '42 kN' },
      },
      {
        id: 'c4-3',
        name: 'Double-Axis Needle Roller Bearing Set',
        partNumber: 'EL-MECH-03',
        panelId: 4,
        material: 'Chrome Steel Cages with Low-Friction Fluoropolymer Coating',
        tolerance: '±0.005 mm',
        mass: '68 g',
        description: 'Paired needle roller bearings providing extreme radial stiffness in an ultra-compact package.',
        specs: { 'Radial Dynamic Load': '12.8 kN' },
      },
      {
        id: 'c4-4',
        name: 'Integrated Shock-Absorbing Hydraulic Damper',
        partNumber: 'EL-MECH-04',
        panelId: 4,
        material: 'Hard-Chromed Stainless Steel Rod + Micro-Orifice Piston',
        tolerance: '±0.012 mm',
        mass: '115 g',
        description: 'Progressive fluid damper absorbing kinetic energy at end-of-travel stops.',
        specs: { 'Damping Coefficient': '420 N·s/m', 'Fluid': 'Synthetic Ester ISO VG 32' },
      },
      {
        id: 'c4-5',
        name: 'CNC Mechanical 135° Hard-Stop Lug',
        partNumber: 'EL-MECH-05',
        panelId: 4,
        material: 'Case-Hardened 8620 Steel with Elastomer Pad',
        tolerance: '±0.010 mm',
        mass: '34 g',
        description: 'Positive physical limit stop preventing hyperextension and hyperflexion cable impingement.',
        specs: { 'Impact Capacity': '180 Nm Dynamic Stop' },
      },
      {
        id: 'c4-6',
        name: 'Concentric Laser-Etched Rotary Protractor Bezel',
        partNumber: 'EL-MECH-06',
        panelId: 4,
        material: 'Black Anodized 7075 Aluminum with Precision Laser Scale',
        tolerance: '±0.02 mm',
        mass: '22 g',
        description: 'Calibrated angle scale with 5° graduation tick marks for visual angular inspection.',
        specs: { 'Angular Accuracy': '±0.25°' },
      },
    ],
  },
  {
    id: 5,
    title: 'PANEL 5 — FOREARM INTERNAL CHASSIS & ACTUATOR BAYS',
    subtitle: '7075-T6 Triangulated Spaceframe, Dual Linear Roller-Screws & Floating Gauntlet',
    standard: 'ASME B89.3.4M',
    projection: 'Cutaway Orthographic Projection',
    scale: '1:1.6',
    dimensions: [
      { label: 'Forearm Overall Length', value: '260.0 mm' },
      { label: 'CNC Truss Cross-Section', value: '52.0 x 48.0 mm' },
      { label: 'Roller-Screw Thread Pitch', value: '2.0 mm Lead' },
      { label: 'Roller-Screw Stroke', value: '55.0 mm' },
      { label: 'Floating Armor Air Gap', value: '3.50 mm Standoff' },
    ],
    kinematics: {
      dof: 'Houses 2 Linear DOF (driving wrist pitch/yaw differential pushrods)',
      range: 'Linear Travel: 55 mm stroke at 120 mm/s',
      torque: 'Linear Thrust: 1,450 N Peak per actuator',
      speed: 'Pitch/Yaw Response: 18 ms step response time',
    },
    components: [
      {
        id: 'c5-1',
        name: 'Triangulated Aerospace Truss Skeleton',
        partNumber: 'FA-SKEL-01',
        panelId: 5,
        material: 'Milled 7075-T651 Aluminum Billets with Lightening Pockets',
        tolerance: '±0.015 mm',
        mass: '310 g',
        description: 'FEA-optimized spaceframe absorbing combined torsion from wrist roll and linear actuator thrust.',
        specs: { 'Torsional Stiffness': '2,400 Nm/rad', 'Lightening Ratio': '58% Mass Removed' },
      },
      {
        id: 'c5-2',
        name: 'Dual Inverted Roller-Screw Linear Actuators',
        partNumber: 'FA-ACT-02',
        panelId: 5,
        material: 'Nitrided Alloy Steel Roller Screws + Brushless DC Motors',
        tolerance: '±0.005 mm',
        mass: '360 g (Pair)',
        description: 'Parallel inverted planetary roller-screws converting high-speed rotary motor power to high-thrust pushrod action.',
        specs: { 'Dynamic Load': '2.8 kN', 'Lead Precision': 'C3 Class (±8 µm / 300 mm)' },
      },
      {
        id: 'c5-3',
        name: 'Central Wrist Roll Transmission Shaft',
        partNumber: 'FA-TRN-03',
        panelId: 5,
        material: 'Hollow Carbon Fiber Composite Drive Tube with Titanium Splines',
        tolerance: '±0.010 mm',
        mass: '75 g',
        description: 'Coaxial drive tube passing through center of forearm to drive distal wrist roll rotation.',
        specs: { 'Outer Diameter': 'Ø 20.0 mm', 'Inner Conduit Bore': 'Ø 14.0 mm' },
      },
      {
        id: 'c5-4',
        name: 'Floating Keel Gauntlet Armor Shell',
        partNumber: 'FA-ARM-04',
        panelId: 5,
        material: 'Ceramic Composite Polycarbonate (White Satin)',
        tolerance: '±0.030 mm',
        mass: '120 g',
        description: 'Aerodynamic shell mounted on CNC elastomeric standoffs, floating 3.5 mm off the skeleton.',
        specs: { 'Thermal Venting': '3x Micro-Louvers with Titanium Mesh' },
      },
      {
        id: 'c5-5',
        name: 'Braided Cybernetic Wiring Conduit Harness',
        partNumber: 'FA-HARN-05',
        panelId: 5,
        material: 'PTFE Fluoropolymer Shielding with Kevlar Braided Outer Sleeve',
        tolerance: 'N/A',
        mass: '65 g',
        description: 'High-flex cable bundle routing 48V power rails, 100 Mbps EtherCAT bus, and hand sensor lines.',
        specs: { 'Bend Cycles': '> 10,000,000 Cycles at 25 mm Radius' },
      },
    ],
  },
  {
    id: 6,
    title: 'PANEL 6 — 3-DOF SPHERICAL WRIST ASSEMBLY',
    subtitle: 'Virtual Center Differential Gimbal, Harmonic Roll & Cable Routing Ring',
    standard: 'ISO 9283',
    projection: 'Exploded Tri-Axial Orthographic',
    scale: '1:1.2',
    dimensions: [
      { label: 'Wrist Outer Enveloping Sphere', value: 'Ø 56.0 mm' },
      { label: 'Yaw Pivot Clevis Width', value: '44.0 mm' },
      { label: 'Pitch Gimbal Pin Diameter', value: 'Ø 12.0 mm' },
      { label: 'Cable Routing Ring ID', value: 'Ø 22.0 mm' },
      { label: 'Palm Interface Flange', value: 'PCD Ø 38 mm (6x M3)' },
    ],
    kinematics: {
      dof: '3 Independent Orthogonal DOF (Roll, Pitch, Yaw)',
      range: 'Roll: ±90° | Pitch: -75° to +75° | Yaw: -30° to +40°',
      torque: 'Roll: 22 Nm | Pitch: 28 Nm | Yaw: 24 Nm',
      speed: 'Angular Speed: 380 deg/sec',
    },
    components: [
      {
        id: 'c6-1',
        name: 'Forearm Distal Interface Collar',
        partNumber: 'WR-INT-01',
        panelId: 6,
        material: '7075-T6 Aluminum with Hard-Anodized Bearing Cup',
        tolerance: '±0.008 mm',
        mass: '68 g',
        description: 'Rigid adapter anchoring wrist module to forearm truss skeleton.',
        specs: { 'Interface': '4x M3 High-Tensile Cap Screws' },
      },
      {
        id: 'c6-2',
        name: 'Compact Cycloidal Harmonic Gear Housing',
        partNumber: 'WR-CYC-02',
        panelId: 6,
        material: 'Tool Steel Pin Ring + Dual Wobble Discs',
        tolerance: '±0.005 mm',
        mass: '95 g',
        description: 'Sub-miniature cycloidal reducer providing zero backlash and high shock overload capacity.',
        specs: { 'Reduction Ratio': '59:1', 'Backlash': '< 1.0 arcmin' },
      },
      {
        id: 'c6-3',
        name: '2-Axis Pitch/Yaw Clevis Gimbal Yoke',
        partNumber: 'WR-YOKE-03',
        panelId: 6,
        material: 'Grade 5 Titanium CNC Machined Mono-Block',
        tolerance: '±0.006 mm',
        mass: '52 g',
        description: 'Cross-pivot clevis carrying orthogonal bearings for decoupled pitch and yaw motion.',
        specs: { 'Max Joint Angle': 'Compound 82° Conical Envelope' },
      },
      {
        id: 'c6-4',
        name: 'Concentric Hollow Cable Routing Ring',
        partNumber: 'WR-RING-04',
        panelId: 6,
        material: 'Lubricated Delrin AF (PTFE-Filled Acetal)',
        tolerance: '±0.015 mm',
        mass: '14 g',
        description: 'Low-friction internal pass-through ring ensuring hand tendon cables and sensor wires twist smoothly without pinching during full wrist roll.',
        specs: { 'Internal Bore': 'Ø 22 mm', 'Friction Coefficient': 'µ = 0.08' },
      },
      {
        id: 'c6-5',
        name: 'Styloid Process Ceramic Armor Cowls',
        partNumber: 'WR-ARM-05',
        panelId: 6,
        material: 'Zirconia Toughened Alumina (White ZTA)',
        tolerance: '±0.025 mm',
        mass: '28 g (Pair)',
        description: 'Ergonomic lateral and medial cowls shielding pivot hubs and bearing seams.',
        specs: { 'Hardness': '1,450 HV', 'Scratch Proof': 'Mohs 9' },
      },
    ],
  },
  {
    id: 7,
    title: 'PANEL 7 — COMPLETE ARTICULATED HAND',
    subtitle: 'Front Wireframe Projections, Metacarpal Skeleton & Knuckle Bearing Layout',
    standard: 'ISO 13482',
    projection: 'Front Orthographic (Palmar & Dorsal View)',
    scale: '1:1.0 (Full Scale 1:1)',
    dimensions: [
      { label: 'Hand Length (Wrist Crease to Tip III)', value: '160.0 mm' },
      { label: 'Palm Width Across Knuckles (II-V)', value: '74.0 mm' },
      { label: 'Thumb Span at Full Abduction', value: '118.0 mm' },
      { label: 'Digit III (Middle) Length', value: '92.0 mm' },
      { label: 'Digit II (Index) Length', value: '84.0 mm' },
      { label: 'Digit IV (Ring) Length', value: '82.0 mm' },
      { label: 'Digit V (Little) Length', value: '68.0 mm' },
      { label: 'Thumb (Digit I) Length', value: '62.0 mm' },
    ],
    kinematics: {
      dof: '12 Active Driven DOF (4 MCP Abduction/Adduction + 5 Flexion + 3 Thumb)',
      range: 'Power Grip Cylindrical: Ø 15 mm to Ø 95 mm',
      torque: 'Fingertip Pinch Force: 32 N | Power Wrap Force: 85 N',
      speed: 'Full Fist Closure Time: 0.14 s',
    },
    components: [
      {
        id: 'c7-1',
        name: 'Metacarpal Structural Palm Chassis',
        partNumber: 'HD-PALM-01',
        panelId: 7,
        material: 'Milled Titanium Ti-6Al-4V Spaceframe with Carbon Bridge',
        tolerance: '±0.010 mm',
        mass: '110 g',
        description: 'Rigid base plate carrying micro spool servo drives, tendon tensioners, and MCP axle pivots.',
        specs: { 'Tendon Tensioners': '10x Automatic Spring-Loaded Tension Wheels' },
      },
      {
        id: 'c7-2',
        name: 'High-Traction Molded Palmar Grip Pads',
        partNumber: 'HD-PAD-02',
        panelId: 7,
        material: 'Conductive Silicone Elastomer 40 Shore A (Textured Hex Pattern)',
        tolerance: '±0.05 mm',
        mass: '18 g',
        description: 'Micro-textured grip pads providing high friction against glass, metal, and irregular objects.',
        specs: { 'Dry Friction Coeff': 'µ = 1.65', 'Wet Friction Coeff': 'µ = 1.15' },
      },
      {
        id: 'c7-3',
        name: 'Opposable Thumb 4-DOF Saddle Joint (CMC)',
        partNumber: 'HD-THM-03',
        panelId: 7,
        material: 'Case-Hardened Steel Pivot with 38° Anatomical Cant',
        tolerance: '±0.008 mm',
        mass: '42 g',
        description: 'Complex saddle joint enabling human-like pad-to-pad opposition against all four fingers.',
        specs: { 'Opposition Arc': '125° Circumduction Envelope' },
      },
      {
        id: 'c7-4',
        name: 'MCP Knuckle Dual-Spindle Bearing Housings',
        partNumber: 'HD-KNCK-04',
        panelId: 7,
        material: 'Miniature Ceramic Ball Bearings (ZrO2)',
        tolerance: '±0.003 mm',
        mass: '24 g (8 bearings)',
        description: 'Dual-axis knuckle bearings providing smooth flexion and lateral finger splay (abduction).',
        specs: { 'Splay Angle': '±12° per digit' },
      },
    ],
  },
  {
    id: 8,
    title: 'PANEL 8 — HAND EXPLODED DISASSEMBLY',
    subtitle: 'Individual Digit Explosion, Phalanx Load Frames & Tendon Routing Channels',
    standard: 'ASME Y14.38',
    projection: 'Exploded Linear Axial Projection',
    scale: '1:1.0 (Full Scale 1:1)',
    dimensions: [
      { label: 'Proximal Phalanx Length (Digit III)', value: '42.0 mm' },
      { label: 'Middle Phalanx Length (Digit III)', value: '28.0 mm' },
      { label: 'Distal Phalanx Length (Digit III)', value: '22.0 mm' },
      { label: 'Tendon Routing Wire Diameter', value: 'Ø 1.10 mm' },
      { label: 'Knuckle Pin Diameter', value: 'Ø 3.00 mm (Precision H7/h6)' },
    ],
    kinematics: {
      dof: '3 Inter-Phalangeal Joints per Finger (MCP, PIP, DIP)',
      range: 'MCP: 0°-90° | PIP: 0°-105° | DIP: 0°-80°',
      torque: 'Tendon Tension: 220 N Max Working Load per cable',
      speed: 'Tendon Displacement Speed: 180 mm/s',
    },
    components: [
      {
        id: 'c8-1',
        name: 'Proximal Phalanx Skeletal Frame',
        partNumber: 'DIG-PROX-01',
        panelId: 8,
        material: '7075-T6 CNC Aluminum Bone with Ceramic Snap-On Cover',
        tolerance: '±0.008 mm',
        mass: '8.4 g',
        description: 'Primary structural link transmitting heavy grip loads from knuckle to intermediate joint.',
        specs: { 'Tendon Guide': 'Dual Low-Friction PEEK Bushings' },
      },
      {
        id: 'c8-2',
        name: 'PIP Intermediate Hinge Joint',
        partNumber: 'DIG-PIP-02',
        panelId: 8,
        material: 'Stainless Steel Hinge Pin + Miniature Flanged Bushings',
        tolerance: '±0.004 mm',
        mass: '3.2 g',
        description: 'Single-axis precision hinge with internal torsion return spring.',
        specs: { 'Return Spring': '0.045 Nm Preload' },
      },
      {
        id: 'c8-3',
        name: 'Middle Phalanx Load Frame',
        partNumber: 'DIG-MID-03',
        panelId: 8,
        material: 'Carbon-Fiber Reinforced PEEK',
        tolerance: '±0.008 mm',
        mass: '5.1 g',
        description: 'Lightweight intermediate member with curved internal tendon conduit.',
        specs: { 'Tensile Strength': '280 MPa' },
      },
      {
        id: 'c8-4',
        name: 'DIP Distal Hinge Joint',
        partNumber: 'DIG-DIP-04',
        panelId: 8,
        material: 'Case-Hardened Dowel Pin with C-Clip Retention',
        tolerance: '±0.004 mm',
        mass: '1.8 g',
        description: 'Distal hinge synchronizing flexion angle with PIP joint via mechanical linkage.',
        specs: { 'Coupling Ratio': '1:0.75 PIP:DIP Kinematic Tie' },
      },
      {
        id: 'c8-5',
        name: 'Distal Phalanx Sensor Dome Housing',
        partNumber: 'DIG-DIST-05',
        panelId: 8,
        material: 'Precision Polycarbonate Chassis with Silicone Fingertip Bulb',
        tolerance: '±0.010 mm',
        mass: '4.6 g',
        description: 'Houses 3-axis force sensor and 16-element mutual capacitive touch array.',
        specs: { 'Sensor Resolution': '0.05 N Force Threshold' },
      },
      {
        id: 'c8-6',
        name: 'Tungsten-Dyneema Tendon Cable Assembly',
        partNumber: 'DIG-TDN-06',
        panelId: 8,
        material: '7x19 Stranded Tungsten Core with UHMWPE Dyneema Jacket',
        tolerance: '±0.02 mm',
        mass: '1.2 g per cable',
        description: 'Zero-stretch high-modulus tendon cable transmitting micro servo pull to fingertip.',
        specs: { 'Tensile Modulus': '116 GPa', 'Breaking Load': '680 N' },
      },
    ],
  },
  {
    id: 9,
    title: 'PANEL 9 — SINGLE FINGER MICRO-ENGINEERING STUDY',
    subtitle: 'Front View, Lateral Side View, Longitudinal Cross-Section & Tendon Mechanics',
    standard: 'ISO 286-2',
    projection: 'High-Magnification Sectional CAD View',
    scale: '2:1 (200% Magnified Detail)',
    dimensions: [
      { label: 'Overall Finger Height', value: '84.0 mm' },
      { label: 'Finger Width at Knuckle', value: '16.0 mm' },
      { label: 'Finger Thickness (Palmar-Dorsal)', value: '14.5 mm' },
      { label: 'Tendon Pulley Diameter', value: 'Ø 4.5 mm' },
      { label: 'Sensor Pad Radius of Curvature', value: 'R 7.2 mm' },
    ],
    kinematics: {
      dof: 'Full Finger Range of Motion Arc Study',
      range: 'Total Compound Flexion Arc: 275° Enclosure Angle',
      torque: 'Tip Contact Pressure: 0.85 MPa at Max Grip',
      speed: 'Bandwidth: 12 Hz Cyclic Tapping Frequency',
    },
    components: [
      {
        id: 'c9-1',
        name: 'MCP Dual-Axis Gimbal Knuckle',
        partNumber: 'STUDY-MCP-01',
        panelId: 9,
        material: 'Micro Cross-Roller Bearing Assembly',
        tolerance: '±0.003 mm',
        mass: '4.8 g',
        description: 'Permits 0°-90° flexion and ±12° lateral splay without binding the tendon cables.',
        specs: { 'Flexion Stop': '90° Chamfered Mechanical Boss' },
      },
      {
        id: 'c9-2',
        name: 'Low-Friction Ceramic Tendon Idler Pulleys',
        partNumber: 'STUDY-PUL-02',
        panelId: 9,
        material: 'Silicon Nitride (Si3N4) Ceramic with Micro Flanges',
        tolerance: '±0.002 mm',
        mass: '0.4 g each',
        description: 'Smooth rotating pulleys eliminating friction and heat buildup during fast repetitive grasping.',
        specs: { 'Rolling Friction': 'µ = 0.0015' },
      },
      {
        id: 'c9-3',
        name: 'Internal Return Torsion Springs',
        partNumber: 'STUDY-SPR-03',
        panelId: 9,
        material: 'Music Wire ASTM A228 Phosphate Coated',
        tolerance: '±0.01 mm',
        mass: '0.6 g each',
        description: 'Dual helical torsion springs returning finger to extended resting state when tendon relaxes.',
        specs: { 'Spring Rate': '0.008 Nm/rad' },
      },
      {
        id: 'c9-4',
        name: 'Fingertip Multi-Modal Sensory Pad',
        partNumber: 'STUDY-SEN-04',
        panelId: 9,
        material: 'Soft Polyurethane Gel Skin + Piezoresistive Matrix',
        tolerance: '±0.02 mm',
        mass: '2.1 g',
        description: 'Deformable tactile surface mimicking human finger pulp for friction-adaptive grip sensing.',
        specs: { 'Contact Patch': '12 mm x 14 mm', 'Spatial Res': '1.2 mm Pitch' },
      },
    ],
  },
];
